### ISSUE TITLE
upgrade to angular 2 rc5

### ISSUE THREAD

**Issue by nexus-uw** [rangle/angular2-redux-example#259]

**Comment by nikolasleblanc** [comment]
Closed with #261

**Comment by gajeravijayb** [comment]
Hello Team

I am using angular2 RC4 version and i am going to implement @angular2-material component but on that some component is support and its looks proper like button component but when i add menu component at that time given me error like menu.js is not found i check everything like its file is available on same path or not all thing is fine but why that error is given me i dont know? can you please suggest me why all component is not support?
Same thing i added in angular2 rc5 version its work perfect as required
So is rc4 version is not support @angular2-material all component or i am missing some thing else?
