### ISSUE TITLE
help redux store contain old data when i refresh browser

### ISSUE THREAD

**Issue by nasreddineskandrani** [rangle/angular2-redux-example#278]
hi,
if i refresh my browser the store data remain in it. He dont reload from scratch. 

Is that normal? if yes! Is their a way to wipe it?

**Comment by nasreddineskandrani** [comment]
i found the cause.

ngRedux.configureStore take an enhancers that persist the state. In my case i dont want to persist so i just removed it.

I am a token based auth. So i removed all the session part of your example/ I seriously dont know why we would persist the hall state in the locale storage. It will be good to be able to say this is object is persistable and this one no. In the root state. To be able to wipe a part of the state auto. and dont do that manually.

**Comment by SethDavenport** [comment]
This was not added recently - it's been there for a while.  Note that this app is an example, so if you're using it to start other projects there may be stuff in it that you want to delete.

If you don't need persistence, remove the redux-localstorage enhancer as you did. If you need to persist only part of the store, I think redux-localstorage can do this; take a look at their docs: https://github.com/elgerlambert/redux-localstorage.

**Comment by nasreddineskandrani** [comment]
thanks
