### ISSUE TITLE
Dead code - Need to clean up or remove

### ISSUE THREAD

**Issue by un33k** [rangle/angular2-redux-example#279]
[This](https://github.com/rangle/angular2-redux-example/blob/master/src/app/sample-app.ts#L46) code block is currently redundant as it is not used.

To activate it ... change this ... 

``` typescript
    const enh = (dev && devTools.isEnabled()) ?
      [ ... enhancers, devTools.enhancer({
        deserializeState: reimmutify,
      }) ] :
      enhancers;

    middleware.push(createEpicMiddleware(this.epics.login));

    ngRedux.configureStore(rootReducer, {}, middleware, enhancers) // <--- here
```

 To:

``` typescript
    const enh = (dev && devTools.isEnabled()) ?
      [ ... enhancers, devTools.enhancer({
        deserializeState: reimmutify,
      }) ] :
      enhancers;

    middleware.push(createEpicMiddleware(this.epics.login));

    ngRedux.configureStore(rootReducer, {}, middleware, enh) // <--- here
```

If we make the above change ... then we get this error: "**DevTools instrumentation should not be applied more than once. Check your store configuration.**"  [Here](https://github.com/rangle/angular2-redux-example/blob/master/src/store/index.ts#L39) is the offending line for the error message.

``` typescript
  const environment: any = window || this;
  if (environment.devToolsExtension) {
    enhancers.push(environment.devToolsExtension());  // <-- here
  }
```

Unsure if ignoring **const enh** is deliberate, a bug, or simply some dead code.

**Comment by danielfigueiredo** [comment]
@un33k Considering the current code:

```typescript 
    ngRedux.configureStore(
      rootReducer,
      {},
      middleware, 
      devTools.isEnabled() ?
        [ ...enhancers, devTools.enhancer() ] :
        enhancers);
```

May I close this issue?

Thanks for reporting

**Comment by un33k** [comment]
Great ... thx.

**Comment by SethDavenport** [comment]
Thanks Daniel.
