### ISSUE TITLE
access data from subscribe into template

### ISSUE THREAD

**Issue by nasreddineskandrani** [rangle/angular2-redux-example#280]
Hi,
i have this code in a component

```
this.subscriberUser = ngRedux.select('user').subscribe(data => {
      let email= Map(data).get('email');
      if(email) {
        newActions.doSomething();
      }
    });
```

i want to use email in the html template of the component.

if i do 
`this.currentUser = data;` 

it works and i can use currentUser.email in the template html of the component.
but the debugger of chrome show me this.currentUser as "undefined" in debug mode.

Is their a good way to do that proprely cause i guess this is not the good way? i see some example with @Select but i need to do a call  newActions.doSomething(); when the data change @Select approch dont allow me that.

**Comment by danielfigueiredo** [comment]
@nasreddineskandrani Would be be able to show a little bit more of what are you trying to accomplish here?
I've manually subscribed to things on the state and my debugging was always fine. That said, I would try to avoid doing something inside your subscription that would dispatch another action for example, this cycle can get longer and thus harder to debug. Just my perspective.
Like: dispatch action -> update store -> trigger subscriptions -> dispatch action -> update store -> trigger subscriptions -> ... who knows what can happen
Perhaps you can organize the actions differently in a sense that you could avoid this?

**Comment by nasreddineskandrani** [comment]
was sick! let me sometimes to check this out a long i posted that. thanks
