### ISSUE TITLE
Fetch/get example

### ISSUE THREAD

**Issue by andrewlo** [rangle/angular2-redux-example#282]
It's very common in apps to do an HTTP get request, have a reducer which adds the response JSON to the redux state, then display the fetched data using @select & async pipe.

Ex. a shopping page may start a fetch for a product list, add dispatch a success action with payload being the data from server (JSON with nested objects & arrays), displaying a loading spinner and error if one occurs.

This example app has an example of async POST request for session/login. However, in my current project we found that it may not be immediately obvious how to write reducers & set up redux state when nested objects are added to the state as typed-immutable-record.

If doing state.merge on the nested object, @select will not work for example, the typed factories must be called.

It may make sense to add an example in this project where the client does an HTTP GET, fetches some nested data, and displays it on a page using select/async, with nested typed immutable records, so that we have a reference for this very common pattern.

**Comment by SethDavenport** [comment]
Yeah I'm starting to have reservations about Immutable and Typescript. Typed-immutable-record addresses some of the concerns but not all.

However @danielfigueiredo if you feel like taking a stab at this go ahead :)

**Comment by danielfigueiredo** [comment]
Same here, I will add this to my TODO list
