### ISSUE TITLE
npm install not working proprely with current package.json - need update

### ISSUE THREAD

**Issue by nasreddineskandrani** [rangle/angular2-redux-example#287]
Hi!
I see a problem in my case with "npm install". problem related to import ng2-redux in my app.module file. 

can someone from rangle try it and confirm it?

Solution:
I had to update couple dependencies to have the current sample project working with angular 2.0.0
"@angular/router": "3.0.0"
 "ng2-redux": "4.0.0"
"stylelint": "7.0.1"
"typescript": "2.0.10"

=> I suggest an update in master 

this is the package.json am using to get it work (without angular2 upgrade to 3.X.X)

>  {
>   "name": "angular2-redux-example",
>   "version": "0.2.0",
>   "description": "A boiler-plate setup for Angular 2/Redux applications",
>   "license": "MIT",
>   "keywords": [
>     "angular2",
>     "redux",
>     "typescript"
>   ],
>   "engines": {
>     "node": "6"
>   },
>   "scripts": {
>     "prebuild": "npm run clean",
>     "build": "cross-env NODE_ENV=production webpack",
>     "clean": "rimraf dist/",
>     "cover": "istanbul report --include=**/chrome/coverage-final.json text text-summary",
>     "dev:server": "cross-env NODE_ENV=development PORT=3000 nodemon server/node-server.js",
>     "dev:client": "cross-env NODE_ENV=development webpack-dev-server -d --inline --progress --no-info",
>     "dev": "concurrently -r \"npm run dev:client\" \"npm run dev:server\"",
>     "lint": "npm run lint-ts && npm run lint-js && npm run lint-css",
>     "lint-css": "stylelint './src/**/*.css'",
>     "lint-ts": "tslint './src/**/*.ts'",
>     "lint-js": "eslint '**/*.js' --ignore-path .gitignore",
> 	"postinstall": "npm run typings && npm run build",
>     "start": "cross-env NODE_ENV=production node server/node-server.js",
>     "pretest": "rimraf coverage/ & npm run lint",
>     "test": "karma start --singleRun true",
>     "posttest": "npm run cover",
>     "test:watch": "karma start --singleRun false",
>     "typings": "rimraf typings/ && typings install"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/rangle/angular2-redux-starter.git"
>   },
>   "bugs": {
>     "url": "https://github.com/rangle/rangle-starter/issues"
>   },
>   "dependencies": {
>     "angular2-google-maps": "^0.15.0",
>     "bootstrap": "^4.0.0-alpha.4",
>     "express": "^4.13.4",
>     "helmet": "^2.0.0",
>     "http-proxy": "^1.13.2",
>     "ng2-bootstrap": "1.1.5",
>     "winston": "^2.1.1"
>   },
>   "devDependencies": {
>     "@angular/common": "2.0.0",
>     "@angular/compiler": "2.0.0",
>     "@angular/core": "2.0.0",
>     "@angular/forms": "2.0.0",
>     "@angular/http": "2.0.0",
>     "@angular/platform-browser": "2.0.0",
>     "@angular/platform-browser-dynamic": "2.0.0",
>     "@angular/router": "3.0.0",
>     "@types/assertion-error": "^1.0.30",
>     "@types/jasmine": "^2.2.34",
>     "@types/node": "^6.0.42",
>     "autoprefixer": "^6.3.3",
>     "autoprefixer-core": "^6.0.1",
>     "awesome-typescript-loader": "^2.2.1",
>     "babel-core": "^6.11.4",
>     "babel-loader": "^6.2.5",
>     "babel-polyfill": "^6.13.0",
>     "babel-preset-es2015": "^6.9.0",
>     "basscss": "^8.0.1",
>     "basscss-addons": "^1.0.0-beta4",
>     "basscss-basic": "^1.0.0",
>     "body-parser": "^1.15.0",
>     "classlist-polyfill": "^1.0.2",
>     "concurrently": "^2.0.0",
>     "console-polyfill": "^0.2.2",
>     "copy-webpack-plugin": "^3.0.1",
>     "core-js": "^2.4.1",
>     "cross-env": "^2.0.0",
>     "css-loader": "^0.23.1",
>     "cssnano": "^3.7.1",
>     "denodeify": "^1.2.1",
>     "eslint": "^3.2.0",
>     "extract-text-webpack-plugin": "^2.0.0-beta.3",
>     "file-loader": "^0.9.0",
>     "html-webpack-plugin": "^2.7.2",
>     "html5-history-api": "^4.2.7",
>     "immutable": "^3.8.1",
>     "inline-source-map": "^0.6.2",
>     "istanbul": "^1.0.0-alpha.2",
>     "istanbul-instrumenter-loader": "^0.2.0",
>     "jasmine-core": "^2.4.1",
>     "json-loader": "^0.5.4",
>     "karma": "^1.1.2",
>     "karma-chrome-launcher": "^1.0.1",
>     "karma-coverage": "^1.0.0",
>     "karma-jasmine": "^0.3.8",
>     "karma-phantomjs-launcher": "^1.0.1",
>     "karma-remap-istanbul": "^0.1.0",
>     "karma-sourcemap-loader": "^0.3.7",
>     "karma-sourcemap-writer": "^0.1.2",
>     "karma-spec-reporter": "0.0.26",
>     "karma-webpack": "^1.7.0",
>     "ng2-redux": "4.0.0",
>     "ng2-redux-router": "^1.3.3",
>     "nodemon": "^1.9.2",
>     "passport": "^0.3.2",
>     "passport-local": "^1.0.0",
>     "postcss-cssnext": "^2.4.0",
>     "postcss-import": "8.0.2",
>     "postcss-loader": "^0.9.1",
>     "raf": "^3.2.0",
>     "ramda": "^0.22.1",
>     "raw-loader": "^0.5.1",
>     "redux": "^3.4.0",
>     "redux-localstorage": "^0.4.0",
>     "redux-logger": "^2.6.1",
>     "redux-observable": "^0.9.0",
>     "reflect-metadata": "0.1.3",
>     "rimraf": "^2.5.4",
>     "rxjs": "5.0.0-beta.12",
>     "style-loader": "^0.13.0",
>     "stylelint": "7.0.1",
>     "stylelint-webpack-plugin": "^0.3.0",
>     "to-string-loader": "^1.1.3",
>     "ts-helpers": "^1.1.1",
>     "tslint": "^3.12.1",
>     "tslint-loader": "^2.1.0",
>     "typed-immutable-record": "0.0.3",
>     "typescript": "2.0.10",
>     "webpack": "2.1.0-beta.25",
>     "webpack-dev-server": "2.1.0-beta.5",
>     "webpack-hot-middleware": "2.12.2",
>     "webpack-split-by-path": "0.1.0-beta.1",
>     "zone.js": "^0.6.17"
>   }
> }
>

**Comment by SethDavenport** [comment]
@bennett000 I guess we need to update this example to the newer ngtools/webpack based toolchain from angular2-starter.

**Comment by danielfigueiredo** [comment]
this[https://github.com/rangle/angular2-redux-example/pull/288] might fix it

**Comment by danielfigueiredo** [comment]
@nasreddineskandrani could you please pull from upstream and try again?

**Comment by SethDavenport** [comment]
I can confirm that this is now fixed.

**Comment by nasreddineskandrani** [comment]
i was sick. didnt try it yet! thank you :) for the validation and  the fix
