### ISSUE TITLE
can any one please do a favour

### ISSUE THREAD

**Issue by malikasinger1** [rangle/angular2-redux-example#290]
# can any one please do a favour

## please explain the code step by step like [angular 2 guide](https://angular.io/docs/ts/latest/guide/router.html)

i want to learn from this code but i'm unable

**Comment by SethDavenport** [comment]
Unfortunately we don't have the bandwidth to maintain something like the angular 2 guide at this time. If you want to learn angular, that guide is your best bet. If you want to learn Angular with Redux, then you can also find some supplemental material here https://github.com/angular-redux/store/blob/master/README.md

We also maintain an Angular 2 gitbook here: ngcourse.rangleapp.io.
