### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by alistairmgreen** [rangle/angular2-redux-example#293]
I am getting a compile error when I run `npm install` on a fresh clone of this repository:

```
ERROR in [default] /home/alistair/dev/angular2-redux-example/node_modules/@types/jasmine/index.d.ts:39:37 
A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [default] /home/alistair/dev/angular2-redux-example/node_modules/@types/jasmine/index.d.ts:39:45 
Cannot find name 'keyof'.

ERROR in [default] /home/alistair/dev/angular2-redux-example/node_modules/@types/jasmine/index.d.ts:39:51 
'=' expected.
```

See [this gist](https://gist.github.com/alistairmgreen/2f596b7ce284c57b405124fdf63672fa) for a transcript of my terminal session and the full Node.js error log.

Environment details:
* Node 6.9.5 (current LTS release; does angular2-redux-example require a newer version?)
* Ubuntu 16.0.4

Thanks in advance for any advice.

**Comment by gnomeontherun** [comment]
Its the latest @jasmine/typings release, so just downgrade that package a couple releases it goes away.

**Comment by alistairmgreen** [comment]
Thanks, I managed to get it to compile by changing the relevant line in `package.json` from:
```json
"@types/jasmine": "^2.5.35"
```
to:
```json
"@types/jasmine": "2.5.41"
```
I have since found the same problem on several other Angular 2 example projects. It seems that the `^` operator (for "latest minor revision of") is surprisingly dangerous!

**Comment by SethDavenport** [comment]
Yeah this repo is overdue for a toolchain update, which is something I'm working on. In the meantime, in order to avoid grief associated with point release breaking changes in dependencies, I recommend using `yarn` instead of `npm`. See https://yarnpkg.com.

The included `yarn.lock` file in this repo will make sure you're running against a known, working set of transitive dependencies.
